apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
  namespace: ordina
spec:
  resources:
    - name: source-repo
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: build-docker-image-micronaut-app
      taskRef:
        name: build-docker-image-from-git-source
      params:
        - name: pathToContext
          value: /workspace/docker-source/
        - name: pathToDockerFile
          value: /workspace/docker-source/Dockerfile
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: docker-image
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
  namespace: ordina
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToContext
        type: string
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/docker-source
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/docker-source/Dockerfile
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.9.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/kaniko/.docker"
      command:
        - /kaniko/executor
      args:
        - --context=$(inputs.params.pathToContext)
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage.url)
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source-pr
  namespace: ordina
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/knative-red-button/micronaut-app
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-image-pr
  namespace: ordina
spec:
  type: image
  params:
    - name: url
      value: docker.io/knativeredbutton/micronaut-app-team-ordina